# Generated by Django 3.0.5 on 2020-05-24 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='static/list_photos', verbose_name='Photo:')),
                ('available', models.BooleanField(default=True, verbose_name='Avaiable:')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('delivery_time', models.IntegerField()),
                ('delivery_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WirtualnyOptyk.Product')),
                ('type', models.IntegerField(choices=[(1, 'Big glass cleaner'), (2, 'small glass cleaner'), (3, 'lens liquid'), (4, 'eyeglass chains'), (5, 'eyeglass cloth')])),
            ],
            bases=('WirtualnyOptyk.product',),
        ),
        migrations.CreateModel(
            name='ContactLenses',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WirtualnyOptyk.Product')),
                ('type', models.IntegerField(choices=[(1, 'one day'), (2, 'repeated use'), (3, 'one year')])),
            ],
            bases=('WirtualnyOptyk.product',),
        ),
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WirtualnyOptyk.Product')),
                ('type', models.IntegerField(choices=[(1, 'plastic_frames'), (2, 'metal_frames'), (3, 'siluetts')])),
            ],
            bases=('WirtualnyOptyk.product',),
        ),
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WirtualnyOptyk.Product')),
                ('type', models.IntegerField(choices=[(1, 'corrective'), (2, 'progressive'), (3, 'photochromes'), (4, 'shaded')])),
            ],
            bases=('WirtualnyOptyk.product',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=40)),
                ('adress', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WirtualnyOptyk.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WirtualnyOptyk.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='WirtualnyOptyk.OrderProduct', to='WirtualnyOptyk.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WirtualnyOptyk.Supply'),
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WirtualnyOptyk.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WirtualnyOptyk.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='WirtualnyOptyk.CartProducts', to='WirtualnyOptyk.Product'),
        ),
    ]
